
language: node_js
node_js:
 - "node"
cache: yarn
install:
  - yarn install
before_script:
  - npm install -g typescript truffle tslint ethereumjs-testrpc
  - testrpc &
script:
  - set -e
  - yarn tslint
